apiVersion: 1

prune: true

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    editable: false
    jsonData:
      httpMethod: GET
